### ISSUE TITLE
HTTP Status 404

### ISSUE THREAD

**Issue by matolsen** [writecodedrinkcoffee/vagrant-lemtl#4] opened 2016-08-05 00:47 UTC
Once I get the machine up I get the following message when I try to browse any of the urls. Any suggestions?

HTTP Status 404 -
type Status report
message
description The requested resource is not available.
Apache Tomcat/7.0.52 (Ubuntu)

I'm running:
On a Mac v 10.11.6
Vagrant 1.8.5
VirtualBox 5.0.25 (with the extension pack)

nginx log:
192.168.50.1 - - [04/Aug/2016:20:15:58 -0400] "GET /lucee/admin/server.cfm HTTP/1.1" 404 967 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
192.168.50.1 - - [04/Aug/2016:20:16:02 -0400] "GET / HTTP/1.1" 404 967 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
192.168.50.1 - - [04/Aug/2016:20:16:38 -0400] "GET / HTTP/1.1" 404 967 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"

**Comment by mikesprague** [comment] 2016-08-05 02:09
Haven't seen that before. Have you tried running `vagrant reload --provision` to see if that resolves it? 

I've occasionally seen issues with Vagrant boxes not fully provisioning on the first attempt and had luck with a reload.

Let me know if you have any luck with that (or if you've already tried it).

**Comment by mikesprague** [comment] 2016-08-10 04:18
Never heard anything back and I can't reproduce so going to close this.

I will gladly reopen it if you can provide more details. Thanks.

**Closed as completed by mikesprague** 2016-08-10 04:18 UTC

**Comment by 14nd90** [comment] 2016-12-16 09:53
Hi there

Having the same issue. Log attached.
[vagrant up.txt](https://github.com/mikesprague/vagrant-lemtl/files/656828/vagrant.up.txt)
